import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { CONFIG } from '@12tails/shared/config';
import type { PlayerState, ServerToClientEvents } from '@12tails/shared/events';
import { connectSocket, type GameSocket } from '../net/socket';
import { CHARACTERS, getCharacter, type CharacterDef } from '../manifest';
import { gameToUI, uiToGame } from '../ui/bus';
import { ChatOverlay } from '../ui/ChatOverlay';
import { EmotePanel } from '../ui/EmotePanel';
import { DayNightToggle, type MapVariant } from '../ui/DayNightToggle';
import { loadCharacterAsset, type CharacterAsset } from './CharacterAsset';
import { LocalPlayer3D, RemotePlayer3D, PX_TO_UNIT } from './Player3D';
import { OverheadLayer } from './Overhead';

/** ชื่อแมพบน HUD (ค่าเดิมจาก WorldScene — ย้ายไป map data เมื่อมีหลายแมพ) */
const MAP_NAME = 'ค่ายมือใหม่';
const DEMO_SELF = { level: 1, xp: 20, xpMax: 100 };
const DEMO_WALLET = { jil: 1200, coins: 300 };

const CAMERA_OFFSET = new THREE.Vector3(0, 8, 7.5);
const CAMERA_LOOK_UP = 1.1; // look slightly above the feet
const GROUND_SIZE = 220;    // tiles (= world units)

interface MapVariantDef {
  url: string;
  bg: number;           // sky + fog color
  hemiSky: number;
  hemiGround: number;
  hemiIntensity: number;
  sunColor: number;
  sunIntensity: number;
  groundColor: number;  // placeholder plane under the map
}

/** Day/night map pair exported from the game (G30_NoGuild / G30_NoGuild_n). */
const MAP_VARIANTS: Record<MapVariant, MapVariantDef> = {
  day: {
    url: 'assets/models/map-day.glb',
    bg: 0x8fc4e8, hemiSky: 0xffffff, hemiGround: 0x88aa77, hemiIntensity: 2.1,
    sunColor: 0xfff2d8, sunIntensity: 1.6, groundColor: 0x69a85c,
  },
  night: {
    url: 'assets/models/map-night.glb',
    bg: 0x111a30, hemiSky: 0x8fa3d9, hemiGround: 0x2c3350, hemiIntensity: 0.95,
    sunColor: 0xb8ccff, sunIntensity: 0.55, groundColor: 0x2f4a3a,
  },
};

/** เริ่มที่กลางคืน — ตามที่เจ้าของโปรเจกต์ชอบ 🌙 */
const DEFAULT_MAP_VARIANT: MapVariant = 'night';

/** In dev, force-fresh fetches — re-exported maps/masks must never come from cache. */
function bust(url: string): string {
  return import.meta.env.DEV ? `${url}?t=${Date.now()}` : url;
}

/** Walkability grid generated by tools/gen-walkmask (white = walkable). */
const WALKMASK_URL = 'assets/maps3d/walkmask';

interface Walkmask {
  data: Uint8ClampedArray;
  width: number;
  height: number;
  originX: number;
  originZ: number;
  cell: number;
}

/** G30_NoGuild's walkable floor sits at y≈50 in scene coords (measured from the
 *  NoGuildCircle plaza / river / tent bases) — drop it to our y=0 walk plane.
 *  XZ stays native so game coordinates keep matching the original scene
 *  (spawn is moved instead, see CONFIG.SPAWN). */
const MAP_OFFSET = new THREE.Vector3(0, -50, 0);

export interface WorldInit {
  characterId: string;
  name: string;
}

interface SentState {
  x: number;
  y: number;
  dir: string;
  moving: boolean;
}

/** Destroys the Phaser boot flow and hands the #game container to the 3D world. */
export async function launchWorld3D(
  init: WorldInit,
  phaserGame: { destroy(removeCanvas: boolean): void },
) {
  phaserGame.destroy(true);
  const world = new World3D(init);
  await world.start();
}

/**
 * The shared 3D map — same Socket.IO contract as the 2D WorldScene it
 * replaces (join/move/chat/emote), same DOM UI via the bus. Rendering is
 * three.js; the server stays a relay and never knows the difference.
 */
export class World3D {
  private renderer!: THREE.WebGLRenderer;
  private scene = new THREE.Scene();
  private camera!: THREE.PerspectiveCamera;
  private clock = new THREE.Clock();
  private selfDef!: CharacterDef;
  private asset!: CharacterAsset;
  /** Remotes whose model is still loading; value = drop the join if cleared. */
  private pendingJoins = new Map<string, PlayerState>();

  private socket!: GameSocket;
  private player!: LocalPlayer3D;
  private remotes = new Map<string, RemotePlayer3D>();
  private overheads = new OverheadLayer();
  private chat!: ChatOverlay;
  private emotePanel!: EmotePanel;

  private keys = new Set<string>();
  private inputEnabled = true;
  private moveInput = new THREE.Vector2();
  private sendAccum = 0;
  private lastSent: SentState | null = null;

  // Day/night: lighting refs + one loaded group per map variant.
  private hemi!: THREE.HemisphereLight;
  private sun!: THREE.DirectionalLight;
  private fog = new THREE.Fog(0x8fc4e8, 40, 120);
  private groundMat!: THREE.MeshLambertMaterial;
  private mapVariant: MapVariant = DEFAULT_MAP_VARIANT;
  private mapGroups = new Map<MapVariant, THREE.Group | 'loading'>();
  private mapMixers = new Map<MapVariant, THREE.AnimationMixer>();
  private dayNight!: DayNightToggle;
  private walkmask: Walkmask | null = null;
  private groundRay = new THREE.Raycaster();
  private static readonly DOWN = new THREE.Vector3(0, -1, 0);

  constructor(private init: WorldInit) {}

  async start() {
    this.selfDef = getCharacter(this.init.characterId) ?? CHARACTERS[0];
    try {
      this.asset = await loadCharacterAsset(this.selfDef);
    } catch (err) {
      console.error('[world3d] FAILED to load own model', this.selfDef.model, err);
      throw err;
    }
    this.setupRenderer();
    this.setupWorld();
    this.setupPlayer();
    this.setupInput();
    this.setupNetwork();
    this.setupChat();
    this.setupEmotes();
    this.setupUIBridge();
    this.dayNight = new DayNightToggle({
      initial: DEFAULT_MAP_VARIANT,
      onChange: (v) => this.setMapVariant(v),
    });
    this.renderer.setAnimationLoop(() => this.tick());
  }

  // ---------------------------------------------------------------- scene

  private setupRenderer() {
    const container = document.getElementById('game') ?? document.body;
    this.renderer = new THREE.WebGLRenderer({ antialias: true });
    this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    this.renderer.setSize(window.innerWidth, window.innerHeight);
    container.appendChild(this.renderer.domElement);

    this.camera = new THREE.PerspectiveCamera(
      50, window.innerWidth / window.innerHeight, 0.1, 400,
    );

    window.addEventListener('resize', () => {
      this.camera.aspect = window.innerWidth / window.innerHeight;
      this.camera.updateProjectionMatrix();
      this.renderer.setSize(window.innerWidth, window.innerHeight);
    });
  }

  private setupWorld() {
    this.scene.fog = this.fog;

    this.hemi = new THREE.HemisphereLight(0xffffff, 0x88aa77, 2.1);
    this.scene.add(this.hemi);
    this.sun = new THREE.DirectionalLight(0xfff2d8, 1.6);
    this.sun.position.set(20, 40, 25);
    this.scene.add(this.sun);

    // Placeholder ground — stays underneath the real map as a safety floor.
    const cx = CONFIG.SPAWN.x * PX_TO_UNIT;
    const cz = CONFIG.SPAWN.y * PX_TO_UNIT;
    this.groundMat = new THREE.MeshLambertMaterial({ color: 0x69a85c });
    const ground = new THREE.Mesh(new THREE.PlaneGeometry(GROUND_SIZE, GROUND_SIZE), this.groundMat);
    ground.rotation.x = -Math.PI / 2;
    // Sits well under the real map floor (y=0) so the two never z-fight.
    ground.position.set(cx, -0.25, cz);
    this.scene.add(ground);

    this.setMapVariant(DEFAULT_MAP_VARIANT);
    void this.loadWalkmask();
  }

  /** Load the walkability grid if present; without it movement is unrestricted. */
  private async loadWalkmask() {
    try {
      const meta = await (await fetch(bust(`${WALKMASK_URL}.json`))).json();
      const img = await new Promise<HTMLImageElement>((resolve, reject) => {
        const i = new Image();
        i.onload = () => resolve(i);
        i.onerror = reject;
        i.src = bust(`${WALKMASK_URL}.png`);
      });
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      if (!ctx) return;
      ctx.drawImage(img, 0, 0);
      this.walkmask = {
        data: ctx.getImageData(0, 0, img.width, img.height).data,
        width: img.width,
        height: img.height,
        originX: meta.originX,
        originZ: meta.originZ,
        cell: meta.cell,
      };
      // Never let a bad mask trap the player at spawn.
      if (!this.canWalkPx(CONFIG.SPAWN.x, CONFIG.SPAWN.y)) {
        console.warn('[world3d] walkmask blocks the spawn point — mask disabled');
        this.walkmask = null;
        return;
      }
      console.log('[world3d] walkmask active');
    } catch {
      console.log('[world3d] no walkmask — free walking (run tools/gen-walkmask)');
    }
  }

  /** Terrain height (world units) under a px position — raycast down onto the map. */
  private sampleGroundY(pxX: number, pxY: number): number {
    const map = this.mapGroups.get(this.mapVariant);
    if (!map || map === 'loading') return 0;
    this.groundRay.set(
      new THREE.Vector3(pxX * PX_TO_UNIT, 60, pxY * PX_TO_UNIT),
      World3D.DOWN,
    );
    const hits = this.groundRay.intersectObject(map, true);
    for (const h of hits) {
      if (h.object.visible === false) continue; // hidden spawn markers etc.
      return h.point.y;
    }
    return 0;
  }

  /** px-space walkability check handed to the local player each frame. */
  private canWalkPx = (pxX: number, pxY: number): boolean => {
    const m = this.walkmask;
    if (!m) return true;
    const gx = Math.floor((pxX * PX_TO_UNIT - m.originX) / m.cell);
    const gz = Math.floor((pxY * PX_TO_UNIT - m.originZ) / m.cell);
    if (gx < 0 || gz < 0 || gx >= m.width || gz >= m.height) return false;
    return m.data[(gz * m.width + gx) * 4] > 127;
  };

  /** Swap lighting + visible map group; lazy-loads each variant's glb once. */
  private setMapVariant(v: MapVariant) {
    this.mapVariant = v;
    const def = MAP_VARIANTS[v];

    this.scene.background = new THREE.Color(def.bg);
    this.fog.color.set(def.bg);
    this.hemi.color.set(def.hemiSky);
    this.hemi.groundColor.set(def.hemiGround);
    this.hemi.intensity = def.hemiIntensity;
    this.sun.color.set(def.sunColor);
    this.sun.intensity = def.sunIntensity;
    this.groundMat.color.set(def.groundColor);

    for (const [k, g] of this.mapGroups) {
      if (g !== 'loading') g.visible = k === v;
    }
    if (!this.mapGroups.has(v)) void this.loadMap(v);
  }

  /** Load one map variant's glb if present (fire-and-forget — the world is
   *  playable on the placeholder ground while it streams in). */
  private async loadMap(v: MapVariant) {
    const def = MAP_VARIANTS[v];
    this.mapGroups.set(v, 'loading');
    try {
      const gltf = await new GLTFLoader().loadAsync(bust(def.url));
      const map = gltf.scene;
      map.position.copy(MAP_OFFSET);
      map.traverse((obj) => {
        // Spawn/exit markers are dev gizmos in the game scene — never render them.
        if (/^(StartPoint|StartCamera|ExitZone|ExitLine)/i.test(obj.name)) {
          obj.visible = false;
          return;
        }
        if (!(obj instanceof THREE.Mesh)) return;
        // Same flat-toon flattening as characters — kill Unity PBR gloss.
        const mats = Array.isArray(obj.material) ? obj.material : [obj.material];
        for (const m of mats) {
          const std = m as THREE.MeshStandardMaterial;
          if (std && 'roughness' in std) {
            std.roughness = 1;
            std.metalness = 0;
          }
        }
      });
      map.visible = v === this.mapVariant;
      this.mapGroups.set(v, map);
      this.scene.add(map);

      // NPC idle clips shipped inside the scene — play them all so the camp
      // feels alive instead of T-posing statues.
      if (gltf.animations.length) {
        const mixer = new THREE.AnimationMixer(map);
        for (const clip of gltf.animations) mixer.clipAction(clip).play();
        this.mapMixers.set(v, mixer);
      }
      const box = new THREE.Box3().setFromObject(map);
      console.log(
        `[world3d] map '${v}' loaded — bounds min`, box.min, 'max', box.max,
        `| spawn is at (${(CONFIG.SPAWN.x * PX_TO_UNIT).toFixed(1)}, 0, ` +
        `${(CONFIG.SPAWN.y * PX_TO_UNIT).toFixed(1)}) — tune MAP_OFFSET to align`,
      );
    } catch {
      this.mapGroups.delete(v);
      console.log(`[world3d] no map at ${def.url} — placeholder ground only`);
    }
  }

  private setupPlayer() {
    this.player = new LocalPlayer3D(this.asset, CONFIG.SPAWN.x, CONFIG.SPAWN.y);
    this.scene.add(this.player.group);
    this.overheads.ensure('self', this.init.name);

    // Start the camera snapped to the player.
    const p = this.player.group.position;
    this.camera.position.copy(p).add(CAMERA_OFFSET);
    this.camera.lookAt(p.x, p.y + CAMERA_LOOK_UP, p.z);
  }

  // ---------------------------------------------------------------- input

  private setupInput() {
    window.addEventListener('keydown', (e) => this.keys.add(e.code));
    window.addEventListener('keyup', (e) => this.keys.delete(e.code));
    window.addEventListener('blur', () => this.keys.clear());

    // Dev aid: press P to print where you stand — walk to a good spot, send the
    // numbers, and CONFIG.SPAWN gets pinned there.
    window.addEventListener('keydown', (e) => {
      if (e.code !== 'KeyP' || !this.inputEnabled) return;
      const px = this.player.posPx;
      console.log(
        `[world3d] ตำแหน่งปัจจุบัน px=(${Math.round(px.x)}, ${Math.round(px.y)}) ` +
        `units=(${(px.x * PX_TO_UNIT).toFixed(1)}, ${(px.y * PX_TO_UNIT).toFixed(1)}) ` +
        `→ CONFIG.SPAWN = { x: ${Math.round(px.x)}, y: ${Math.round(px.y)} }`,
      );
    });
  }

  private readMoveInput() {
    this.moveInput.set(0, 0);
    if (!this.inputEnabled) return;
    if (this.keys.has('ArrowLeft') || this.keys.has('KeyA')) this.moveInput.x -= 1;
    if (this.keys.has('ArrowRight') || this.keys.has('KeyD')) this.moveInput.x += 1;
    if (this.keys.has('ArrowUp') || this.keys.has('KeyW')) this.moveInput.y -= 1;
    if (this.keys.has('ArrowDown') || this.keys.has('KeyS')) this.moveInput.y += 1;
  }

  // ------------------------------------------------------------ networking

  private setupNetwork() {
    this.socket = connectSocket();

    const join = () => {
      this.socket.emit('player:join', {
        characterId: this.init.characterId,
        name: this.init.name,
        x: Math.round(this.player.posPx.x),
        y: Math.round(this.player.posPx.y),
        dir: this.player.direction,
      });
      this.lastSent = null; // force a fresh move send after (re)join
    };

    const onSnapshot: ServerToClientEvents['world:snapshot'] = ({ players }) => {
      const seen = new Set<string>();
      for (const p of players) {
        if (p.id === this.socket.id) continue;
        seen.add(p.id);
        const existing = this.remotes.get(p.id);
        if (existing) existing.applyMove(p);
        else this.addRemote(p);
      }
      for (const [id, r] of this.remotes) {
        if (!seen.has(id)) this.removeRemote(id, r);
      }
      for (const id of this.pendingJoins.keys()) {
        if (!seen.has(id)) this.pendingJoins.delete(id);
      }
      this.emitOnline();
    };

    const onJoined: ServerToClientEvents['player:joined'] = ({ player }) => {
      if (player.id !== this.socket.id) this.addRemote(player);
    };

    const onMoved: ServerToClientEvents['player:moved'] = (p) => {
      this.remotes.get(p.id)?.applyMove(p);
    };

    const onLeft: ServerToClientEvents['player:left'] = ({ id }) => {
      this.pendingJoins.delete(id); // cancel a join still waiting on its model
      const r = this.remotes.get(id);
      if (r) this.removeRemote(id, r);
      this.emitOnline();
    };

    this.socket.on('world:snapshot', onSnapshot);
    this.socket.on('player:joined', onJoined);
    this.socket.on('player:moved', onMoved);
    this.socket.on('player:left', onLeft);
    this.socket.on('connect', join);
    join(); // buffered by socket.io if not connected yet
  }

  private async addRemote(state: PlayerState) {
    if (this.remotes.has(state.id) || this.pendingJoins.has(state.id)) return;
    this.pendingJoins.set(state.id, state);

    const def = getCharacter(state.characterId) ?? CHARACTERS[0];
    let asset: CharacterAsset;
    try {
      asset = await loadCharacterAsset(def);
    } catch (err) {
      console.error('[world3d] FAILED to load remote model', def.model, err);
      this.pendingJoins.delete(state.id);
      return;
    }

    // While the model loaded the player may have left (pendingJoins cleared).
    if (!this.pendingJoins.delete(state.id) || this.remotes.has(state.id)) return;

    const r = new RemotePlayer3D(asset, state, def.id);
    this.remotes.set(state.id, r);
    this.scene.add(r.group);
    this.overheads.ensure(state.id, state.name);
    this.emitOnline();
  }

  private removeRemote(id: string, r: RemotePlayer3D) {
    this.scene.remove(r.group);
    this.remotes.delete(id);
    this.overheads.remove(id);
  }

  private sendMove(deltaMs: number) {
    this.sendAccum += deltaMs;
    const interval = 1000 / CONFIG.MOVE_SEND_HZ;
    if (this.sendAccum < interval) return;
    this.sendAccum %= interval;

    const state: SentState = {
      x: Math.round(this.player.posPx.x),
      y: Math.round(this.player.posPx.y),
      dir: this.player.direction,
      moving: this.player.moving,
    };
    const prev = this.lastSent;
    if (
      prev && prev.x === state.x && prev.y === state.y &&
      prev.dir === state.dir && prev.moving === state.moving
    ) {
      return;
    }
    this.socket.emit('player:move', {
      x: state.x, y: state.y, dir: this.player.direction, moving: state.moving,
    });
    this.lastSent = state;
  }

  // ------------------------------------------------------------------ chat

  private setupChat() {
    this.chat = new ChatOverlay({
      onSend: (text) => this.socket.emit('chat:send', { text }),
      onFocusChange: (focused) => {
        this.inputEnabled = !focused;
        this.keys.clear();
      },
    });

    const onChat: ServerToClientEvents['chat:message'] = (m) => {
      this.chat.addMessage(m);
      const key = m.id === this.socket.id ? 'self' : m.id;
      if (key === 'self' || this.remotes.has(m.id)) {
        this.overheads.ensure(key, m.name).showBubble(m.text);
      }
    };
    this.socket.on('chat:message', onChat);
  }

  // ---------------------------------------------------------------- emotes

  private setupEmotes() {
    this.emotePanel = new EmotePanel({
      onPick: (emoteId) => this.socket.emit('emote:send', { emoteId }),
    });

    const onEmote: ServerToClientEvents['emote:played'] = ({ id, emoteId }) => {
      const isSelf = id === this.socket.id;
      const target = isSelf ? this.player : this.remotes.get(id);
      if (!target) return;

      // Ids come straight off the wire — act only on known ones.
      if ((CONFIG.EMOTE_ACTIONS as readonly string[]).includes(emoteId)) {
        target.playAction(emoteId);
        return;
      }
      if (!(CONFIG.EMOTE_BUBBLES as readonly string[]).includes(emoteId)) return;
      const key = isSelf ? 'self' : id;
      this.overheads
        .ensure(key, isSelf ? this.init.name : '')
        .showEmote(`assets/ui/bubbles/${emoteId}.png`);
    };
    this.socket.on('emote:played', onEmote);
  }

  // ------------------------------------------------------------- UI bridge

  private setupUIBridge() {
    gameToUI.emit('room:name', { name: MAP_NAME });
    gameToUI.emit('player:self', {
      characterId: this.init.characterId,
      name: this.init.name,
      ...DEMO_SELF,
    });
    gameToUI.emit('player:currency', DEMO_WALLET);
    this.emitOnline();

    uiToGame.on('music:toggle', () => {
      console.log('[world3d] bus OK: music:toggle received');
    });
  }

  private emitOnline() {
    gameToUI.emit('players:count', { online: 1 + this.remotes.size });
  }

  // ------------------------------------------------------------------ loop

  private tick() {
    const dt = Math.min(this.clock.getDelta(), 0.05);

    this.readMoveInput();
    this.player.groundY = this.sampleGroundY(this.player.posPx.x, this.player.posPx.y);
    this.player.update(dt, this.moveInput, this.canWalkPx);
    for (const r of this.remotes.values()) {
      r.groundY = this.sampleGroundY(r.posPx.x, r.posPx.y);
      r.update(dt);
    }
    this.mapMixers.get(this.mapVariant)?.update(dt);

    // Camera: smooth-follow at a fixed 3/4 angle.
    const p = this.player.group.position;
    const wanted = new THREE.Vector3().copy(p).add(CAMERA_OFFSET);
    this.camera.position.lerp(wanted, 1 - Math.pow(0.0001, dt));
    this.camera.lookAt(p.x, p.y + CAMERA_LOOK_UP, p.z);

    // Overheads follow their owners.
    this.overheads.place('self', this.player.headPos, this.camera);
    for (const [id, r] of this.remotes) this.overheads.place(id, r.headPos, this.camera);

    this.sendMove(dt * 1000);
    this.renderer.render(this.scene, this.camera);
  }
}
